name = "simple-docketcc"
compatibility_date = "2024-03-08"

# Cloudflare Pages configuration
pages_build_output_dir = ".svelte-kit/cloudflare"

# Enable Node.js compatibility to support dependencies like node-fetch
compatibility_flags = ["nodejs_compat"]

# Development environment variables (use placeholders for security)
[vars]
ECFS_API_KEY = "placeholder"
GEMINI_API_KEY = "placeholder"
JINA_API_KEY = "placeholder"

[[d1_databases]]
binding = "DB"
database_name = "simple-docketcc-db"
database_id = "e5bfcb56-11ad-4288-a74c-3749f2ddfd1b"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "simple-docketcc-db"
database_id = "e5bfcb56-11ad-4288-a74c-3749f2ddfd1b" 