name = "simple-docketcc"
compatibility_date = "2024-03-08"

# Cloudflare Pages configuration
pages_build_output_dir = ".svelte-kit/cloudflare"

# Enable Node.js compatibility to support dependencies like node-fetch
compatibility_flags = ["nodejs_compat"]

# NEW: Cron triggers for production scheduling (was completely missing!)
[triggers]
crons = ["0 */2 * * *"]  # Every 2 hours - will be filtered by ET timezone logic

# Development environment variables (use placeholders for security)
[vars]
ECFS_API_KEY = "placeholder"
GEMINI_API_KEY = "placeholder"
JINA_API_KEY = "placeholder"
# NEW: Missing email and cron configuration
CRON_SECRET = "dev_cron_secret_change_in_production"
RESEND_API_KEY = "placeholder"
FROM_EMAIL = "dev@simpledcc.pages.dev"
FROM_NAME = "SimpleDCC Dev"
APP_URL = "http://localhost:5173"

[[d1_databases]]
binding = "DB"
database_name = "simple-docketcc-db"
database_id = "e5bfcb56-11ad-4288-a74c-3749f2ddfd1b"

# Production environment configuration
[env.production]
[env.production.vars]
# Existing API keys
ECFS_API_KEY = "production_ecfs_key"
GEMINI_API_KEY = "production_gemini_key"
JINA_API_KEY = "production_jina_key"
# NEW: Missing email and cron configuration for production
CRON_SECRET = "production_cron_secret"
RESEND_API_KEY = "production_resend_key"
FROM_EMAIL = "notifications@simpledcc.pages.dev"
FROM_NAME = "SimpleDCC"
APP_URL = "https://simpledcc.pages.dev"

[[env.production.d1_databases]]
binding = "DB"
database_name = "simple-docketcc-db"
database_id = "e5bfcb56-11ad-4288-a74c-3749f2ddfd1b" 