name = "simple-docketcc"
compatibility_date = "2024-03-08"

# Node.js compatibility for dotenv, node-fetch, etc.
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
ECFS_API_BASE_URL = "https://publicapi.fcc.gov/ecfs"
ECFS_API_KEY = "7DMIhVNAxnGY64lDwhNxpFVrgFLfc4pUUWXn5lzW"

[[d1_databases]]
binding = "DB"
database_name = "simple-docketcc-db"
database_id = "e5bfcb56-11ad-4288-a74c-3749f2ddfd1b"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "simple-docketcc-db"
database_id = "e5bfcb56-11ad-4288-a74c-3749f2ddfd1b" 