# File: cron-worker/wrangler.toml
# FINAL PRODUCTION CONFIGURATION
# This file has no named environments. It directly configures the
# production worker and inherits all secrets and variables
# from the Cloudflare Dashboard.

name = "simpledcc-cron-worker"
main = "src/index.ts"
compatibility_date = "2024-03-08"

[triggers]
crons = ["0 * * * *"]

# --- PERSISTENT LOGGING CONFIGURATION ---
# This ensures that logging settings are preserved on every deploy
# and prevents the need to manually re-enable logs in the dashboard
# Using correct Wrangler v3.88.0+ / v4.x syntax
[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "simple-docketcc-db"
database_id = "e5bfcb56-11ad-4288-a74c-3749f2ddfd1b" 